### ISSUE TITLE
Force NODE_PATH environment variable

### ISSUE THREAD

**Issue by jagged3dge** [tkw1536/atomerinal#1]
Is it possible to do force NODE_PATH from atom's exports folder to a different folder?

I've tried using:
`NODE_PATH="D:\WebDevTools\nodejs,D:\npm-modules\node_modules"`
but it seems it gets rejected and NODE_PATH in the opened terminal still shows:
`NODE_PATH=C:\Users\Gary\AppData\Local\atom\app-1.0.19\resources\app.asar\exports`

**Comment by jagged3dge** [comment]
I just researched a little more and found a related issue reported to Atom editor repo: https://github.com/atom/atom/issues/3311

**Comment by tkw1536** [comment]
@jagged3dge Where did you try changing the environment variable? 

![screen shot 2015-11-19 at 19 48 38](https://cloud.githubusercontent.com/assets/2923242/11280505/950f6d7c-8ef6-11e5-8753-46b0b6954a68.jpg)

If you change the `environmentVariables` setting of this package to `NODE_PATH=D:\WebDevTools\nodejs,ATOMERNIAL_FILE=$file,ATOMERNIAL_DIRECTORY=$directory,NODE_ENV=` at least atoms value should be overriden. Unfortunatly you can not set environment variables to anything containing a comma right now.

**Comment by tkw1536** [comment]
This issue hasn't had any activity for a long time, closing.

**Comment by jagged3dge** [comment]
Oops, did not realize this issue was still open. I've since moved on to VSCode as my editor, ditching Atom. 
Regardless, thank you for your package and continued support :+1:
