### ISSUE TITLE
“Open terminal here” in context menu

### ISSUE THREAD

**Issue by fabioquarantini** [tkw1536/atomerinal#6]
Hi,
would you consider adding an options to run "Open terminal here" and "Open terminal root" in context menu (tree view and editor).

**Comment by tkw1536** [comment]
I remember having this already inside the plugin. I think some (more or less) recent versions of atom may have changed the API causing it to break. 
I will have a closer look on the weekend.

**Comment by tkw1536** [comment]
Alright, the menu items have been added back.
